version: '3'
services:
  web:
    build: .
    tty: true
    command: npm run dev
    # command: yarn serve
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      # - "8080:8080"

# dcb      
# dcrw vue init webpack .
# dcrw vue create .

# config/index.js port: 8080 ==> 3000